apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT_HTTP}
    user: default
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DB}
      protocol: http
      host: ${CLICKHOUSE_HOST}
      port: ${CLICKHOUSE_PORT_HTTP}
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: true
    editable: true
    version: 1 