apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    user: default
    secureJsonData:
      password: default
    jsonData:
      defaultDatabase: online_store
      protocol: http
      host: clickhouse
      port: 8123
      username: default
      tlsSkipVerify: true
    editable: true
    version: 1 