{
 "title": "Online Store Analytics",
 "tags": [ "online-store" ],
 "time": { "from": "now-1M", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Daily Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(o.order_date) as time, sum(oi.quantity * p.external_price) as daily_revenue FROM online_store.orders o JOIN online_store.order_items oi ON o.order_id = oi.order_id JOIN online_store.products p ON oi.product_id = p.product_id WHERE $__timeFilter(o.order_date) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Revenue by Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.main_category, sum(oi.quantity * p.external_price) as category_revenue FROM online_store.orders o JOIN online_store.order_items oi ON o.order_id = oi.order_id JOIN online_store.products p ON oi.product_id = p.product_id WHERE $__timeFilter(o.order_date) GROUP BY p.main_category"
    }
   ]
  },
  {
   "title": "Daily Active Customers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(o.order_date) as time, count(DISTINCT o.user_id) as total_customers FROM online_store.orders o WHERE $__timeFilter(o.order_date) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Daily Average Customer Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(u.last_login) as time, avg(u.user_age) as average_age FROM online_store.users u WHERE $__timeFilter(u.last_login) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Revenue by Seller",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT concat_ws(' ', s.first_name, s.last_name) as seller_name, sum(oi.quantity * p.external_price) as seller_revenue FROM online_store.orders o JOIN online_store.order_items oi ON o.order_id = oi.order_id JOIN online_store.products p ON oi.product_id = p.product_id JOIN online_store.sellers s ON oi.seller_id = s.seller_id WHERE $__timeFilter(o.order_date) GROUP BY s.seller_id, s.first_name, s.last_name ORDER BY seller_revenue DESC"
    }
   ]
  },
  {
   "title": "Items Sold by Seller",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT concat_ws(' ', s.first_name, s.last_name) as seller_name, sum(oi.quantity) as items_sold FROM online_store.orders o JOIN online_store.order_items oi ON o.order_id = oi.order_id JOIN online_store.products p ON oi.product_id = p.product_id JOIN online_store.sellers s ON oi.seller_id = s.seller_id WHERE $__timeFilter(o.order_date) GROUP BY s.seller_id, s.first_name, s.last_name ORDER BY items_sold DESC"
    }
   ]
  },
  {
   "title": "Daily Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(order_date) as time, count() as total_orders FROM online_store.orders WHERE $__timeFilter(order_date) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Daily New Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(date_joined) as time, count() as new_users FROM online_store.users WHERE $__timeFilter(date_joined) GROUP BY time ORDER BY time"
    }
   ]
  }
 ]
}